// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240314044744_AlimentarTablaVila")]
    partial class AlimentarTablaVila
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("imagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("metrocuadrado")
                        .HasColumnType("float");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ocupante")
                        .HasColumnType("int");

                    b.Property<double>("tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            amenidad = "",
                            detalle = "Es verde",
                            fechaActualizacion = new DateTime(2024, 3, 13, 22, 47, 44, 617, DateTimeKind.Local).AddTicks(872),
                            fechaCreacion = new DateTime(2024, 3, 13, 22, 47, 44, 617, DateTimeKind.Local).AddTicks(859),
                            imagenUrl = "",
                            metrocuadrado = 50.0,
                            nombre = "Villa real",
                            ocupante = 5,
                            tarifa = 50.0
                        },
                        new
                        {
                            Id = 2,
                            amenidad = "",
                            detalle = "Es azul",
                            fechaActualizacion = new DateTime(2024, 3, 13, 22, 47, 44, 617, DateTimeKind.Local).AddTicks(875),
                            fechaCreacion = new DateTime(2024, 3, 13, 22, 47, 44, 617, DateTimeKind.Local).AddTicks(874),
                            imagenUrl = "",
                            metrocuadrado = 25.0,
                            nombre = "Villa azul",
                            ocupante = 6,
                            tarifa = 80.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
